### ISSUE TITLE
Question about Fine-tuning Implementation in Code for Reproducing Paper Results

### ISSUE THREAD

**Issue by gyuta** [artberryx/CSD-public#2]
I am very interested in this study and would like to reproduce the results of the paper on my own. However, I noticed that the code does not include any fine-tuning for downstream tasks, so am I correct in understanding that I need to implement it myself?

**Comment by seohongpark** [comment]
Thank you for your interest in this work! Cleaning up the code for hierarchical controllers is still on our to-do list (also, we would like to note that we do not fine-tune skills for downstream tasks but train an additional hierarchical controller on top of the fixed skills). In the meanwhile, I can send you the implementation in our development branch via email, and please let me know in case you need it.
